### ISSUE TITLE
Brainstorm Project Ideas

### ISSUE THREAD

**Issue by Zacknetic** [Zacknetic/Calorie-Calc-Frontend#1]
Description:
Brainstorm possible project ideas. Do not choose an idea yet.

Completion Criteria:
- [x] An attached list of 3 or more project ideas.

**Comment by CocoTapi** [comment]
The app allows you to show how many grams of food a cat owner should give per a day
users will type
- wet food cal
- dry food cal (--kcla/kg or --kcal/cup)
- cat's weight
the app shows
- gram of dry food for normal and diet per a day / meal

**Comment by CocoTapi** [comment]
auto salad suggestion: 
when you tell vegetables you already have at home, the app tells you how much of them you are better to eat per a day

**Comment by Zacknetic** [comment]
Recipe storage and search app. Features:

- create and store recipes
- Lists and other rich text
- Images
- Search by the ingredients you have
- Create a grocery list from the recipes you've chosen

**Comment by Zacknetic** [comment]
Criteria has been met. Closing ticket.
